sudo: False

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"


before_script:
  - pip install coveralls
  - ./build.py install_dependencies -v

script:
  - ./build.py -v -X
  - (cd target/dist/PyBuilder-* && python setup.py install)

after_success:
  - coveralls --verbose
